### ISSUE TITLE
Consider including an example IOC under `iocs`

### ISSUE THREAD

**Issue by jwlodek** [dls-controls/ADOdin#20]
Currently, it seems to be able to set up a test IOC you need to set up the dls iocbuilder mechanisms. It would be good to have an example IOC available that does not require this setup.

**Comment by GDYendell** [comment]
We have actually just added an example IOC for xspress on the master branch for Quantum Detectors to try out. Does this work for you? Maybe it would be more useful to have an example eiger IOC?

**Comment by jwlodek** [comment]
Yes, it would be great to have an eiger one, that is what we are using to do some tests with Odin.

**Comment by GDYendell** [comment]
Added to the master branch in https://github.com/dls-controls/ADOdin/commit/5eb1f4a4c5b9a82cb8bc3991e7febd134061cb75

**Comment by jwlodek** [comment]
Thank you!
