### ISSUE TITLE
Add units attribute to `detector_readout_time` and `threshold_energy`

### ISSUE THREAD

**Issue by noemifrisina** [dls-controls/ADOdin#22]
It would be good if some of the datasets in the `*_meta.h5` file for Eiger had attributes indicating the units:
`detector_readout_time` in `s`
`threshold_energy` in `eV`
`photon_energy` in `eV`

**Comment by GDYendell** [comment]
For this we need to
- Add an optional units field to [`HDF5Dataset`](https://github.com/odin-detector/odin-data/blob/master/python/src/odin_data/meta_writer/hdf5dataset.py#L124) (and its derived classes)
  - Or, probably better a generic dictionary of attributes to add
- In [`HDF5Dataset.write`](https://github.com/odin-detector/odin-data/blob/master/python/src/odin_data/meta_writer/hdf5dataset.py#L257) if units is not `None`, call `self._h5py_dataset.attrs["units"] = self._units`
- In `EigerMetaWriter` add the units to the dataset definitions e.g. [`detector_readout_time`](https://github.com/dls-controls/eiger-detector/blob/master/python/src/eiger_detector/data/eiger_meta_writer.py#L191)

**Comment by GDYendell** [comment]
Implemented by referenced PRs in other projects.
