### ISSUE TITLE
Update to be compatible with latest odin-data

### ISSUE THREAD

**Issue by GDYendell** [dls-controls/ADOdin#24]
Currently these changes are in pending PRs, so ADOdin would need to be tested against the `command-dev` branch of odin-data. The easiest way to test this is to run the fastcs-odin full development environment and check out this branch instead of fastcs-dev to run the local deployment, and run ADOdin instead of (or as well as) the fastcs-odin IOC.

These are the changes, all of which should be testable with the local deployment: 
 
##### Parameter URIs changed (https://github.com/odin-detector/odin-data/pull/369):
- hdf/file/name -> hdf/file/prefix
- decoder/name -> decoder/class (possibly unused?)

Acceptance Criteria: The new parameter can be set and read back

##### File writer `write` config changed to `start_writing` and `stop_writing` commands (https://github.com/odin-detector/odin-data/pull/372)
- config/hdf/file/write = true/false ->
  - command/hdf/start_writing
  - command/hdf/stop_writing

These commands are implemented in the driver code [here](https://github.com/DiamondLightSource/ADOdin/blob/dls-master/odinApp/src/OdinDataRestApi.cpp#L83)

Acceptance Criteria: File writing can be started and stopped

##### Top-level parameters have been removed from the adapter and clients must now poke each underlying value (https://github.com/odin-detector/odin-data/pull/373)

There are different ways that could be solved. The most obvious is to add some database logic in fan out the puts to the indexed records. The first step here is to check how many of these there are and report back so we can discuss the best approach.

Acceptance Criteria: All indexed configs can be set with one top-level PV

**Comment by jsouter** [comment]
Looks like the EigerFanAdapter PVs are broken when running the eiger example ioc in ADOdin v1 against odin-data/parameter-tree (that adapter basically just inherits from OdinDataAdapter and adds no additional functionality). It seems like the parameters are getting added to the ParameterTree correctly, will have to investigate what's going wrong there.

**Comment by GDYendell** [comment]
This is going to be too difficult. The current interface between ADOdin and the old adapters is too messy to recreate with ParameterTree in a sane way.
